### ISSUE TITLE
[Error] Max retries exceeded with url

### ISSUE THREAD

**Issue by Pheggas** [setnicka/ulozto-downloader#112]
I've got this error message at 161. part of 250 parts set. Does this mean UlozTo banned my IP for establishing too many connections?

![image](https://user-images.githubusercontent.com/9994511/189542111-b2435f2c-0ff9-4145-affc-5ad22de807e2.png)

**Comment by setnicka** [comment]
Sorry for late reply.

This means that ulozto-downloader could not connect to the given URL, this may be caused by packet loss, target server overload or other network problem. Currently I don't know about any IP-counting on download.uloz.to servers, this was probably only some local error or outage.

By restarting the download the ulozto-downloader should reuse any already downloaded parts (and tries to download this part again), if you will encounter this problem again.
